### ISSUE TITLE
[question/Maybe bug?] Any way to reduce loading time for Minecraft with this mod?

### ISSUE THREAD

**Issue by Globalfirestorm10** [RagexPrince683/mcheli-old#1]
I've noticed that with this fork of mcheli, it takes between 2-7 minutes for Minecraft to launch and for me to load into a world. I currently am using 10 other mods with this, and have allocated 6gb of ram to Minecraft forge 1.7.10. 

Just in case it matters, here are my specs:
Nvidia Geforce Rtx 3080TI
32gb of ddr4 CL18 3600MHZ memory
AMD RYZEN 9 5900x

My mod list:
Optifine (latest for 1.7.10)
Thermal expansion
Thermal Dynamics
Thermal Foundation
Computercraft
Electrical Age
Opencomputers
HBMs nuclear tech mod (the main one, not forked)
This mod
CoFH Core
Redstonepastemod

note: All mods here are up to date for 1.7.10

**Comment by RagexPrince683** [comment]
This is an old version. I don't update this one anymore.

**Comment by RagexPrince683** [comment]
This is an old version. I don't update this one anymore.
You can find my latest version here: https://ragexprince.wordpress.com/

**Comment by Globalfirestorm10** [comment]
I see, thanks

**Comment by Globalfirestorm10** [comment]
> This is an old version. I don't update this one anymore.
> 
> You can find my latest version here: https://ragexprince.wordpress.com/

The website you use for the download of the pack is very shady, consider using something like Dropbox or mediafire. Up to you though

**Comment by RagexPrince683** [comment]
> 

I cannot make money off dropbox or mediafire and given I do not have a functional server at the time and I am focused on mchelio it's self, it isn't a priority. I do, however suggest using some form of by pass such as Universal Bypass.

**Comment by Globalfirestorm10** [comment]
I got that, thanks. However, I saw  your x-creative studio post about me not understanding the concept of money. I understand that just fine, I just forgot to consider the monetization from ads factor.

**Comment by RagexPrince683** [comment]
Nowhere did I mention you, I found that in a thread on the topic from a different person. Sorry for the misunderstanding, have a nice day.

**Comment by Globalfirestorm10** [comment]
oh, apologies.
